Implement BackstopJS for visual regression testing
RockefellerArchiveCenter/library_project_scripting pull request #184
Opened 2024-01-30 15:36 UTC by HaSistrunk

Adds [backstopJS](https://github.com/garris/BackstopJS) for visual regression testing and adds testing reference images that include all the major layouts and page elements for 3 viewport sizes.

BackstopJS has previously been set up in DIMES and rockarch.org by [rendering the images in a BackstopJS Docker container](https://github.com/garris/BackstopJS?tab=readme-ov-file#using-docker-for-testing-across-different-environments). However, that doesn't work for this site, because the library search won't function in that environment. I was still getting tests to pass consistently without it, but would appreciate others running the tests to check that they work in your environment.

Note: When we implement our RAC style library into this site, we'll need to review the scenario selectors and likely update them because of CSS classname changes.

2024-01-31 21:46 UTC, helrond requested changes
I'm able to get this to run, but I'm consistently getting errors where elements are a couple of pixels off in positioning.

Added one comment so folks build the site using the correct process.

2024-01-31 21:46 UTC, helrond commented on README.md
> +1. Build the site and start the application using `bundle exec jekyll serve --skip-initial-build`
```suggestion
1. Build the site using the steps in the [Local Development section](#local-development) and start the application using `bundle exec jekyll serve --skip-initial-build`
```

2024-03-01 17:11 UTC, HaSistrunk commented
> I'm able to get this to run, but I'm consistently getting errors where elements are a couple of pixels off in positioning.

I couldn't reproduce, but I've updated this to run the tests in Docker, which should hopefully solve that issue. 

Curious what errors, if any, you see now. 

I am seeing periodic but not consistent test fails because of what I believe is a font loading timing issue (comparing the Reference and Tests images that fail show font differences). I haven't found a good solution for this, but I'm wondering if it makes sense to wait and see if this issue persists after implementing the Style Library that imports fonts differently. I know that's not ideal for visual regression testing during Styles implementation, but if the only test fails we see are those fonts, we can work with that and troubleshoot later.

2024-03-06 16:41 UTC, p-galligan approved these changes
I don't fully understand all the JS/Backstop code, but I was able to generally follow what was happening.

I managed to build/locally deploy the site and run the tests.

All 15 tests passed for me.

2024-03-06 18:53 UTC, HaSistrunk commented
> I don't fully understand all the JS/Backstop code, but I was able to generally follow what was happening.

Most important is understanding that the page snapshots that are taken and compared for visual regression testing are specified in the `backstop.json` file, and then if the `readySelector` or `clickSelector` selectors change in the website UI because of changes to the HTML/CSS, then we'll want to update those selectors so that they are still capturing the page elements correctly.

2024-03-06 21:04 UTC, helrond commented
I continue to see small errors in element position. They do not appear to be font-related in the sense that the font appears to be the same size in both screenshots.

We had previously decided not to add visual regression testing to a CI pipeline because it was too inconsistent, so regardless there's going to be some human judgment applied to the visual regression process. I wonder if we've reached the point of diminishing returns in terms of the process, and that we consider this implementation good enough?

2024-03-06 21:15 UTC, HaSistrunk commented
> I continue to see small errors in element position. They do not appear to be font-related in the sense that the font appears to be the same size in both screenshots.
> 
> We had previously decided not to add visual regression testing to a CI pipeline because it was too inconsistent, so regardless there's going to be some human judgment applied to the visual regression process. I wonder if we've reached the point of diminishing returns in terms of the process, and that we consider this implementation good enough?

Ok, agreed. And I would say continue to pay attention to BackstopJS updates, because it's pretty actively being developed/improved.

2024-03-07 20:16 UTC, merged