Differentiate between production and dev environments
RockefellerArchiveCenter/library_project_scripting pull request #86
Opened 2020-09-28 20:01 UTC by p-galligan

Adds a second config file for development purposes, and tweaks the build script.

So, working off the assumption that we can set `jekyll_env` on the server side, all we'd need to do is set it to `production` on the production server and it'll run off of `_config.yml` settings.

Otherwise, any other environment setting will use the `_config_dev.yml` settings when building. The settings loaded from the later config will override settings in the earlier one.

LMK if you think this won't work for our deployment.

2020-09-28 20:40 UTC, helrond requested changes

2020-09-28 20:40 UTC, helrond commented on script/build
> +if JEKYLL_ENV=production; then
```suggestion
if $JEKYLL_ENV="production"; then
```

2020-09-28 20:40 UTC, helrond commented on script/build
> +  bundle exec jekyll build --config _config.yml,_config_dev.yml
```suggestion
  bundle exec jekyll build --config _config_dev.yml
```

2020-09-28 20:56 UTC, helrond commented on script/build
> +if [ "$JEKYLL_ENV" = "production"]; then
```suggestion
if [ "$JEKYLL_ENV" = "production" ]; then
```

2020-09-28 20:58 UTC, helrond commented
I think this will work. I'm wondering, though, about how wise it is to have two config files with almost identical values. If you pass multiple configs, do those values get merged? Would it be possible to have a _config.yml that has all the base values and then a _config.prod.yml that has ONLY the site.url value?

2020-09-28 21:00 UTC, p-galligan commented
@helrond As far as I can tell. I think your suggestion would work. "Settings in later files override settings in earlier files." So I _think_ that it should work to overwrite, and duplication isn't necessary either one way or another.

2020-09-28 21:01 UTC, helrond commented
OK, so let's try that then?

2020-09-28 21:47 UTC, p-galligan commented
Unfortunately it doesn't selectively overwrite... I just tested locally and it needed a value for every variable in both configs.

2020-09-29 14:28 UTC, helrond approved these changes

2020-09-29 14:29 UTC, helrond commented
Maybe just get rid of the `echo` lines in script/build?

2020-09-29 14:30 UTC, p-galligan commented
@helrond Yep, I have that committed locally, I just haven't pushed yet. Do you mind if I add the comment to `make_pages` and the readme change here as well?

2020-09-29 14:31 UTC, helrond commented
That makes sense - let's get that all in this PR.

2020-09-29 14:50 UTC, merged